package com.example.demo;

import java.util.HashMap;
import java.util.Map;

public class countryName {// This class create a map keeps the chinese name and english name of every country in our database
    public Map<String,String> globalname= new HashMap<String,String>();
    public countryName(){
        globalname.put("Afghanistan","\"阿富汗\"");
        globalname.put("Albania","\"阿尔巴尼亚\"");
        globalname.put("United Arab Emirates","\"阿联酋\"");
        globalname.put("Argentina","\"阿根廷\"");
        globalname.put("Armenia","\"亚美尼亚\"");
        globalname.put("Australia","\"澳大利亚\"");
        globalname.put("Austria","\"奥地利\"");
        globalname.put("Azerbaijan","\"阿塞拜疆\"");
        globalname.put("Belgium","\"比利时\"");
        globalname.put("Burkina Faso","\"布基纳法索\"");
        globalname.put("Bangladesh","\"孟加拉国\"");
        globalname.put("Bulgaria","\"保加利亚\"");
        globalname.put("Bosnia and Herzegovina","\"波黑\"");
        globalname.put("Belarus","\"白俄罗斯\"");
        globalname.put("Bolivia","\"玻利维亚\"");
        globalname.put("Brazil","\"巴西\"");
        globalname.put("Canada","\"加拿大\"");
        globalname.put("Switzerland","\"瑞士\"");
        globalname.put("Chile","\"智利\"");
        globalname.put("China","\"中国\"");
        globalname.put("Cameroon","\"喀麦隆\"");
        globalname.put("Republic of the Congo","\"刚果（金）\"");
        globalname.put("Colombia","\"哥伦比亚\"");
        globalname.put("Costa Rica","\"哥斯达黎加\"");
        globalname.put("Cuba","\"古巴\"");
        globalname.put("Cyprus","\"塞浦路斯\"");
        globalname.put("Czech Republic","\"捷克\"");
        globalname.put("Germany","\"德国\"");
        globalname.put("Djibouti","\"吉布提\"");
        globalname.put("Denmark","\"丹麦\"");
        globalname.put("Dominican Republic","\"多米尼加\"");
        globalname.put("Algeria","\"阿尔及利亚\"");
        globalname.put("Ecuador","\"厄瓜多尔\"");
        globalname.put("Egypt","\"埃及\"");
        globalname.put("Spain","\"西班牙\"");
        globalname.put("Estonia","\"爱沙尼亚\"");
        globalname.put("France","\"法国\"");
        globalname.put("Finland","\"芬兰\"");
        globalname.put("United Kingdom","\"英国\"");
        globalname.put("Georgia","\"格鲁吉亚\"");
        globalname.put("Ghana","\"加纳\"");
        globalname.put("Guinea","\"几内亚\"");
        globalname.put("Guinea Bissau","\"几内亚\"");
        globalname.put("Greece","\"希腊\"");
        globalname.put("Guatemala","\"危地马拉\"");
        globalname.put("Honduras","\"洪都拉斯\"");
        globalname.put("Croatia","\"克罗地亚\"");
        globalname.put("Hungary","\"匈牙利\"");
        globalname.put("Indonesia","\"印度尼西亚\"");
        globalname.put("India","\"印度\"");
        globalname.put("Iran","\"伊朗\"");
        globalname.put("Iraq","\"伊拉克\"");
        globalname.put("Iceland","\"冰岛\"");
        globalname.put("Israel","\"以色列\"");
        globalname.put("Italy","\"意大利\"");
        globalname.put("Jordan","\"约旦\"");
        globalname.put("Japan","\"日本\"");
        globalname.put("Kazakhstan","\"哈萨克斯坦\"");
        globalname.put("Kenya","\"肯尼亚\"");
        globalname.put("Kyrgyzstan","\"吉尔吉斯斯坦\"");
        globalname.put("South Korea","\"韩国\"");
        globalname.put("Kuwait","\"科威特\"");
        globalname.put("Lebanon","\"黎巴嫩\"");
        globalname.put("Sri Lanka","\"斯里兰卡\"");
        globalname.put("Lithuania","\"立陶宛\"");
        globalname.put("Luxembourg","\"卢森堡\"");
        globalname.put("Latvia","\"拉脱维亚\"");
        globalname.put("Morocco","\"摩洛哥\"");
        globalname.put("Moldova","\"摩尔多瓦\"");
        globalname.put("Mexico","\"墨西哥\"");
        globalname.put("Macedonia","\"北马其顿\"");
        globalname.put("Montenegro","\"黑山\"");
        globalname.put("Malaysia","\"马来西亚\"");
        globalname.put("Nigeria","\"尼日利亚\"");
        globalname.put("Netherlands","\"荷兰\"");
        globalname.put("Norway","\"挪威\"");
        globalname.put("Oman","\"阿曼\"");
        globalname.put("Pakistan","\"巴基斯坦\"");
        globalname.put("Panama","\"巴拿马\"");
        globalname.put("Peru","\"秘鲁\"");
        globalname.put("Philippines","\"菲律宾\"");
        globalname.put("Poland","\"波兰\"");
        globalname.put("Puerto Rico","\"波多黎各\"");
        globalname.put("Portugal","\"葡萄牙\"");
        globalname.put("Paraguay","\"巴拉圭\"");
        globalname.put("Qatar","\"卡塔尔\"");
        globalname.put("Romania","\"罗马尼亚\"");
        globalname.put("Russia","\"俄罗斯\"");
        globalname.put("Saudi Arabia","\"沙特阿拉伯\"");
        globalname.put("Senegal","\"塞内加尔\"");
        globalname.put("Republic of Serbia","\"塞尔维亚\"");
        globalname.put("Slovakia","\"斯洛伐克\"");
        globalname.put("Slovenia","\"斯洛文尼亚\"");
        globalname.put("Sweden","\"瑞典\"");
        globalname.put("Thailand","\"泰国\"");
        globalname.put("Trinidad and Tobago","\"特立尼达和多巴哥\"");
        globalname.put("Tunisia","\"突尼斯\"");
        globalname.put("Turkey","\"土耳其\"");
        globalname.put("Ukraine","\"乌克兰\"");
        globalname.put("Uruguay","\"乌拉圭\"");
        globalname.put("United States","\"美国\"");
        globalname.put("Uzbekistan","\"乌兹别克斯坦\"");
        globalname.put("Venezuela","\"委内瑞拉\"");
        globalname.put("Vietnam","\"越南\"");
        globalname.put("South Africa","\"南非\"");

        globalname.put("Mali","\"马里\"");
        globalname.put("Burma","\"缅甸\"");
        globalname.put("Somalia","\"索马里\"");
        globalname.put("Jamaica","\"牙买加\"");
        globalname.put("Tanzania","\"坦桑尼亚\"");
        globalname.put("Gabon","\"加蓬\"");



    }
}
