package com.example.demo;

import java.util.HashMap;
import java.util.Map;

public class chinaarea {
    Map<String,String> chinastring = new HashMap<String,String>();
    String bj = "\"北京市\"";
    String shanghai = "\"上海市\"";
    String yunnan = "\"云南省\"";
    String neimenggu = "\"内蒙古自治区\"";
    String taiwan = "\"台湾\"";
    String jilin = "\"吉林省\"";
    String sichuan = "\"四川省\"";
    String tianjin = "\"天津市\"";
    String ningxia = "\"宁夏回族自治区\"";
    String anhui = "\"安徽省\"";
    String shandong = "\"山东省\"";
    String shanxi = "\"山西省\"";
    String guangdong = "\"广东省\"";
    String guangxi = "\"广西壮族自治区\"";
    String xinjiang = "\"新疆维吾尔自治区\"";
    String jiangsu = "\"江苏省\"";
    String jiangxi = "\"江西省\"";
    String hebei = "\"河北省\"";
    String henan = "\"河南省\"";
    String zhejiang = "\"浙江省\"";
    String hainan = "\"海南省\"";
    String hubei = "\"湖北省\"";
    String hunan = "\"湖南省\"";
    String aomen = "\"澳门\"";
    String gansu = "\"甘肃省\"";
    String fujian = "\"福建省\"";
    String xizang = "\"西藏自治区\"";
    String guizhou = "\"贵州省\"";
    String liaoning = "\"辽宁省\"";
    String chongqing = "\"重庆市\"";
    String shannxi = "\"陕西省\"";
    String qinghai = "\"青海省\"";
    String xianggang = "\"香港\"";
    String heilongjiang = "\"黑龙江省\"";
    //  byte[] bts = beijing.getBytes("utf-8");
    public chinaarea(){

        chinastring.put("beijing",bj);
        chinastring.put("shanghai",shanghai);
        chinastring.put("yunnan",yunnan);
        chinastring.put("neimenggu",neimenggu);
        chinastring.put("taiwan",taiwan);
        chinastring.put("jilin",jilin);
        chinastring.put("sichuan",sichuan);
        chinastring.put("tianjin",tianjin);
        chinastring.put("ningxia",ningxia);
        chinastring.put("anhui",anhui);
        chinastring.put("shandong",shandong);
        chinastring.put("shanxi",shanxi);
        chinastring.put("guangdong",guangdong);
        chinastring.put("guangxi",guangxi);
        chinastring.put("xinjiang",xinjiang);
        chinastring.put("jiangsu",jiangsu);
        chinastring.put("jiangxi",jiangxi);
        chinastring.put("hebei",hebei);
        chinastring.put("henan",henan);
        chinastring.put("zhejiang",zhejiang);
        chinastring.put("hainan",hainan);
        chinastring.put("hubei",hubei);
        chinastring.put("hunan",hunan);
        chinastring.put("aomen",aomen);
        chinastring.put("gansu",gansu);
        chinastring.put("fujian",fujian);
        chinastring.put("xizang",xizang);
        chinastring.put("guizhou",guizhou);
        chinastring.put("liaoning",liaoning);
        chinastring.put("chongqing",chongqing);
        chinastring.put("shannxi",shannxi);
        chinastring.put("qinghai",qinghai);
        chinastring.put("xianggang",xianggang);
        chinastring.put("heilongjiang",heilongjiang);
}}
